### PR TITLE
Create page for Agent Based Modelling

### PR DESCRIPTION
**Pull request by Datseris**
This is currently a first draft which is not final and subject to scrutiny!!!

### CODE REVIEW

**Comment by hyrodium** [comment]
Could we consider merging this PR at this stage?

Here are some reasons to suggest merging:

* I am planning to change the template (https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/issues/6#issuecomment-1872905359).
  * It would be better to avoid conflicts.
* Having even incomplete documentation available could be beneficial to users.
  * I understand that creating a 'perfect' page that everyone agrees on would be kind of difficult and time-consuming. Therefore, adding a note like "This page is still work-in-progress. Please refer to [Agents.jl/issues/884](https://github.com/JuliaDynamics/Agents.jl/issues/884) for the previous discussion." would be a suitable interim solution.

**Comment by Datseris** [comment]
this is finished from my end, you can merge.

**Comment by Datseris** [comment]
@KronosTheLate I've sent you a message on slack:
"""
Hi, I'm happy to co-maintain the JuliaPackageComparisons website. I think this project is critical for the wider community.
Simply tag me in PRs that you can't review due to lack of time or lack of familiarity with the topic
"""

**Comment by KronosTheLate** [comment]
I am sorry, I only created a slack user to ask about something specific once. Thanks for repeating the question here.

I have seen you a few different places in the julia community now, and in every case you have seemed to me like a "good actor" - not drawing irrational conclusions, and generally doing good stuff that helps the Julia ecosystem.

I much appreciate your interest in the project, and I will add you as a contributor right away. You will be the third person with merge-rights, so I feel like it would make sense for me to slow down the appetite for new contributors. I dont know if this is a saying in english, but in norway we say that more chefs make a bigger mess ^_^

**Pull request merged**
