### PR TITLE
Create multipletypesintoone.md

### LINKED ISSUE #73: New section: Multiple types packing into one
4 packages exists to the best of my knowledge for this:

- [MixedStructTypes](https://github.com/JuliaDynamics/MixedStructTypes.jl)
- [SumTypes](https://github.com/MasonProtter/SumTypes.jl)
- [Unityper](https://github.com/YingboMa/Unityper.jl)
- [Expronicon](https://github.com/Roger-luo/Expronicon.jl) (with `ADT.@adt`)

### PR DESCRIPTION
**Pull request by Tortar**
Closes #73

### CODE REVIEW

**Comment by hyrodium** [comment]
Thank you for the PR.
Could you update `PKGINFOS`? The contribution guidance is not 
written well yet, so any questions are welcomed!

https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/blob/main/docs/utils.jl#L12

**Comment by Tortar** [comment]
did it :+1:

**Comment by Tortar** [comment]
seems like the section is not there? is there anything more to add?

**Comment by Tortar** [comment]
ok sorry I should read the contributing before :D

**Comment by Tortar** [comment]
should be okay now, but `Contributing.md` seems a bit outdated because it suggests to modify a non existent file

**Comment by Tortar** [comment]
feel free to choose another title for the section if this is not adequate for you @hyrodium

**Review by hyrodium — APPROVED** [review]
LGTM!

**Comment by hyrodium** [comment]
>`Contributing.md` seems a bit outdated because it suggests to modify a non existent file

Thanks for pointing out! I'll update the guide after https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/issues/22 is resolved.

**Pull request merged**
