### PR TITLE
Add page on non-linear least squares solvers

### PR DESCRIPTION
**Pull request by ojwoodford**

### CODE REVIEW

**Comment by KronosTheLate** [comment]
This looks amazing, thank you so much. I will pull this branch, build the website with your changes, and do a proper review as soon as I find the time. But at first glance, this looks like really good content - thanks a bunch.

**Comment by KronosTheLate** [comment]
1) Note on file-name: In the [CONTRIBUTING](https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/blob/main/CONTRIBUTING.md) file I wrote that "The filename should use underscores for spaces, have only lowercase letters, and match the title of the section as well as possible.". Do you find that guideline reasonable? If yes, the filename needs to change. But I will discuss combining the pages in the nest paragraph, so we can hold our horses on the file renaming.
2) I have a feeling that the number of sections will blow up over time, and I am therefore interested in making fewer sections. It is no problem to have long sections with table of contents. How would you feed about making "Nonlinear Least Squares Solvers" a subsection in the nonlinear solver section, as opposed to giving it its own page?
3) As a general note, I am a fan of having a few fluffy sentences. I do not know much on this subject, and find the current version quite dense. Can we add some fluff? Some light introduction and perhaps a simple example would go a long way.

**Comment by KronosTheLate** [comment]
I would prefer a subsection inside nonlinear solvers, and the embellishment you can muster. And then I think it should be merged!

**Comment by KronosTheLate** [comment]
Should I put your content into the nonlinear solver page, and close this? We can then concider the "adding embellishment" a seperate issue.

**Comment by ojwoodford** [comment]
@KronosTheLate I've made the changes requested.

**Comment by KronosTheLate** [comment]
Great, thanks! I merged, made some minor changes to the heading-level, and added a table of contents. Thanks ^_^

**Pull request merged**
