### PR TITLE
Add search box

### LINKED ISSUE #3: Make website searchable
This would be generally useful. It would paricularly help users who only know of a single relevant package, who could then seach to see if it is mentioned in any section.

### PR DESCRIPTION
**Pull request by hyrodium**
This PR fixes #3.

https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/assets/7488140/d639412c-fb9e-492d-8de7-b63bbf515aa5

The files in `_libs/lunr` are copied from https://github.com/tlienart/Franklin.jl/tree/8c043252f61e0a6217fd9c873a5be66cac5a8f3a/docs/_libs/lunr.

Franklin.jl docs for search with Lunr: https://franklinjl.org/extras/lunr/

### CODE REVIEW

**Comment by KronosTheLate** [comment]
This looks perfect! You are really cleaning up this web page, awesome <3

I do not have any critisism on the look and functionaly, so this is ready to go whenever you feel like it is ^_^

**Comment by hyrodium** [comment]
One problem is searching with a term in the sidebar. For example, the result with 'graphs' shows all pages on the site. (x-ref: https://github.com/tlienart/Franklin.jl/issues/1071)

image

This should be fixed in Franklin.jl, so it should be okay to merge this PR.

**Comment by hyrodium** [comment]
Another possible issue will be a CI failure.
We could have some CI checks or preview pages per PR, but let's merge this PR for now.

**Comment by hyrodium** [comment]
The result is not correct. I'll open another PR. :joy:

image

https://juliapackagecomparisons.github.io/search/index.html?q=Makie.jl

**Comment by hyrodium** [comment]
Fixed!

image

**Comment by KronosTheLate** [comment]
> One problem is searching with a term in the sidebar. For example, the result with 'graphs' shows all pages on the site.

That is indeed very unfortunate. Great that you opened an issue in the appropriate place (Y)

**Pull request merged**
