### PR TITLE
Add more packages for Einsum

### PR DESCRIPTION
**Pull request by hyrodium**

### CODE REVIEW

**Comment by KronosTheLate** [comment]
You have found an impressive number of additional packages! Where did you go looking?

**Comment by hyrodium** [comment]
I just found them in the README of https://github.com/mcabbott/Tullio.jl :smile:

**Comment by KronosTheLate** [comment]
> I just found them in the README of https://github.com/mcabbott/Tullio.jl 😄

Right - there is so much of documenting relevant packages going in in every ecosystem, so I really feel like we are doing something important here in making a good, discoverable, and updated common resource for this issue that arises everywhere ^_^

**Comment by hyrodium** [comment]
I've updated the description a little, and this is ready for review!

**Review by KronosTheLate — APPROVED** [review]
After a local build, again you are making good improvements. Thanks!

It is possible that we will need a little guide on how to make a badge for a new package in CONTRIBUTING.md soon. I will be one of the people needing it ^_^

**Pull request merged**
