### PR TITLE
Put sections in alphabetical order

### PR DESCRIPTION
**Pull request by DanielVandH**
It might be easier if the sections in the sidebar are in alphabetical order.

I used this script to sort them (there's probably a better way :-)).

```julia
cd(@__DIR__)
lines = Vector{String}(undef, 0)
page_lines = Vector{Int}(undef, 0)
page_names = Vector{String}(undef, 0)
ignore = Set(["More goodies", "Tags"])
open("sidebar.html", "r") do io 
    for line in eachline(io)
        push!(lines, line)
        if occursin("sidebar-nav-item", line)
            page_name = match(r"<a[^>]*>(.*?)</a>", line).captures[1]
            page_name ∈ ignore && continue
            push!(page_lines, length(lines))
            push!(page_names, page_name)
        end
    end
end
sort_idx = sortperm(page_names)
lines[page_lines] = lines[page_lines[sort_idx]]
open("sidebar.html", "w") do io
    for line in lines
        println(io, line)
    end
end
```

### CODE REVIEW

**Comment by KronosTheLate** [comment]
The ordering definitively needs updating, so thank you for this effort. I do however have another idea in min, and ai am curious what you think of it:

I was imagining that we would do a search for all packages mentioned in a section, sum their stars, and sort section by the summed stars. That should put sections covering the most used domains at the top.

**Comment by DanielVandH** [comment]
I'm not sure. If I were to come to this page, I would probably be in search of a specific domain and so alphabetical is more appropriate. Your suggestion would be good if I'm just browsing in general without looking for a specific domain. I feel like the former scenario would be more common. What do you think?

**Comment by KronosTheLate** [comment]
I agree that it _has_ to be possible to quickly find a section you are looking for. I feel like a search function is the best solution for that use-case.

If someone is just checking out the ecosystem, I would hate to "hide" important domains like plotting and equation solving in between more niche domains like tessellations. My suspicion is that there will be a lot more lesser domains that will completely drown out the big important domains, from a browsing point of view. So alphabetical ordering would make "browsing the ecosystem" a rather boring exercise. If there is one thing I have learned from social media and the attention economy, it is that we need to be captivated, or we move on. And if users encounter mostly irrelevant domains when they first open the sidebar, I worry that it will make the resource seem irrelevant/cluttered, and make it less usable.

It is possible that alphabetical sorting would be fine if we also have the summed statgazer-count next to the domain name, to draw attention to "hotter" domains. It is also possible that we could have a setting for the sorting order, allowing the users to choose.

In any case, I would reserve the option to manually put highly correlated domains next to each other in the list, such as nonlinear solvers and linear solvers. 

But the current order is clearly a mess. So alphabetical would be an upgrade, and the implementation I am talking about could be far into the future for all I know. So I am on board with merging this for now, and revisiting the issue once the collection of numbers of stargazers is up and running. Does that sound good with you?

I am still curious what you imagine the ideal scenario to be, so if you have thoughts on that, please share them ^_^

**Comment by DanielVandH** [comment]
I think you bring up a good point Perhaps a good idea then is to do:

By default, sort by default, but allow for sorting alphabetically as an option. 

Having correlated domains near each other would also be good - would that be part of this sorting, or is it better to make that separate? e.g. have a separate part for tags, or a way to group the table of contents and then sort within each group (last part probably depends on how you want to define correlation, e.g. triangulations are useful for both visualisation and PDEs, amongst other things).

**Comment by DanielVandH** [comment]
I've now updated this so that it's sorted again. I used

```
cd(@__DIR__)
lines = Vector{String}(undef, 0)
page_lines = Vector{Int}(undef, 0)
page_names = Vector{String}(undef, 0)
ignore = Set(["More goodies", "Tags"])
open("sidebar.html", "r") do io
    for line in eachline(io)
        if occursin("sidebar-nav-item", line)
            page_name = match(r"<a[^>]*>(.*?)</a>", line).captures[1]
            page_name ∈ ignore && continue
            push!(lines, replace(line, page_name => lstrip(page_name))) # remove space at start of title name
            push!(page_lines, length(lines))
            push!(page_names, page_name)
        else
            push!(lines, line)
        end
    end
end
sort_idx = sortperm(page_names)
lines[page_lines] = lines[page_lines[sort_idx]]
open("sidebar.html", "w") do io
    for line in lines
        println(io, line)
    end
end
```

(same as before, but fixes a whitespace issue that might be hard to notice if redoing this sorting manually).

**Comment by KronosTheLate** [comment]
> Having correlated domains near each other would also be good - would that be part of this sorting, or is it better to make that separate? e.g. have a separate part for tags, or a way to group the table of contents and then sort within each group (last part probably depends on how you want to define correlation, e.g. triangulations are useful for both visualisation and PDEs, amongst other things).

I am not sure what the best option is, honestly. It is starting to sound good but a little too complicated. I will create a separate issue on the sorting to discuss the goal, so that we can deal with that down the road. For not, alphabetical is simple, and an improvement, so I say we merge this ^_^ Further discussion on how to sort the sidebar can be had in https://github.com/JuliaPackageComparisons/JuliaPackageComparisons.github.io/issues/22, which is a long-term issue intended to find the best solution.

**Pull request merged**
