### PR TITLE
elaborate on UnitSystems.jl comparison

### PR DESCRIPTION
**Pull request by chakravala**
Had to replace the "not recommend" statement and provide an actual explanation.

### CODE REVIEW

**Comment by KronosTheLate** [comment]
Hello @chakravala, thank you for your interest! I will not merge this PR immediatly, as I have some questions that will hopefully lead to a clarifying discussion.

I am browsing through your package now to learn more about it. I have a few questions that I was hoping you could help me understand:
1) What is the main goal of you package? Defining units for convesion, attaching units to number and perform normal operations with them (similar to what I and I guess many others user Unitful.jl for)? Or is there another overarching goal for the package?
2) In general, do you feel like UnitSystems and Unitful have similar goals and intended usage?
3) I am honestly having a hard time figuring out how to use the package to work with units. The documentation shows a bunch of definitions, such as the following:
```
julia> boltzmann(Metric) # J⋅K⁻¹
kB⋅NA⋅𝘩⋅𝘤⁻¹R∞⋅α⁻²μₑᵤ⁻¹2⁴5³ = 1.38064899953(43) × 10⁻²³ [J⋅K⁻¹] Metric
```

When I try to replicate it, the return value does not have units attached, and prints differently:
```
julia> boltzmann(Metric)
1.3806489995254104e-23
```

Based on this, it seems to me like UnitSystems is intended for getting the values of different constants in different unit systems. Is that for example a fair description of the goal of the package?

In general, I find it difficult and confusing to get started, and I suppose that is one of the main reasons why Unitful is so dominant in popularity. Given the much better ease-of-use of Uniful, why should someone prefer using UnitSystems? What can it do that Unitful can not? What can Unitful do, that UnitSystems can not? This is the kind of questions I would love to answer on the page ^_^

**Comment by chakravala** [comment]
> When I try to replicate it, the return value does not have units attached, and prints differently:

There are 3 packages, you can choose which one depending on the level of complexity you want:

lowest complexity: UnitSystems.jl returns pure consants and no Quantity types

more complexity: Similitude.jl uses UnitSystems.jl to implement a Quantity types

high complexity: MeasureSystems.jl re-implements Similitude quantities but with uncertainty error margins

> Based on this, it seems to me like UnitSystems is intended for getting the values of different constants in different unit systems. Is that for example a fair description of the goal of the package?

No, that's only one aspect of UnitSystems, the universal constants are needed to do the unit conversions themselves.

To get a unit conversion, you need to use a unit conversion call:

```Julia
julia> length(Metric,English)
3.280839895013123
```
And this is the most powerful and complete UnitSystem ever documented in all of time and history so far
```Julia
julia> charge(Metric,SI2019)
0.9999999997273952
```
It provides a complete and full comparison of all historical UnitSystems in existence, allowing you to compare for example the exact values from the original Metric system with the SI2019 revision.

>  What can it do that Unitful can not? 

Simply put, UnitSystems.jl is the most powerful and complete unit conversion tool ever made, it is a new standard that replaces the international 2019 standard for units, it's like a whole new standards system that replaces the international system from 2019 because it is more complete and all encompassing and more scientifically complete than even the SI2019 system itself that was developed by a whole standards body. I single handedly extended the standards body work and fully extended it to all possible UnitSystems and made the most complete UnitSystem ever made, more complete than any historical system before.

My UnitSystems even allows you to convert between English gravitational units vs the British units of weight and mass, and it allows you to convert between multiple different types of historical electrical unit systems, such as CGS, EMU, ESU, and so on. These are all more advanced scientific capabilities which Unitful is simply not capable of, because UnitSytems.jl is the first ever to fully unify and complete all these UnitSystems in a single resource.

**Comment by chakravala** [comment]
If you still want my submission to be shorter, the sentence

> These are the constants `boltzmann`, `planckreduced`, `lightspeed`, `vacuumpermeability`, `electronmass`, `molarmass`, `luminousefficacy`, `angle`, `rationalization`, `lorentz`, and `gravity`.

can be deleted

**Comment by KronosTheLate** [comment]
The way it is now is much better than it was. I am still not 100% happy with it, but I can sense that I will not get around to this in a while. I will merge this so that it does not get forgotten (and remain as bad as it is), and leave improvements for the future ^_^

Thank you for your contributions!

**Pull request merged**
